FROM eclipse-temurin:21-jdk-alpine

# cria usuário
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

WORKDIR /app

COPY target/emergencyroom-0.0.1-SNAPSHOT.jar app.jar

# muda dono do arquivo
RUN chown -R appuser:appgroup /app

# usa usuário não-root
USER appuser

ENTRYPOINT ["java", "-jar", "app.jar"]