apiVersion: apps/v1
kind: Deployment
metadata:
  name: prontosocorro-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prontosocorro
  template:
    metadata:
      labels:
        app: prontosocorro
    spec:
      containers:
        - name: prontosocorro
          image: prontosocorro:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq